import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'conveyor-belt-system-animation',
    title: 'Conveyor Belt System Animation',
    category: 'industrial',
    client: 'Manufacturing Client, Germany',
    tools: ['Blender', 'After Effects', 'DaVinci Resolve'],
    thumbnail: '/conveyor-render.jpeg',
    videoUrl: 'https://www.youtube.com/watch?v=kM-hUSXABWI',
    wireframeUrl: '/conveyor-wireframe.jpeg',
    renderUrl: '/conveyor-render.jpeg',
    description: 'A 15-second looping animation showcasing a multi-stage conveyor belt system for a manufacturing facility, complete with moving parts, product flow, and mechanical details.',
    challenge: 'The client needed a clear, accurate visual of their conveyor system to use in sales presentations and training materials. Technical drawings were too complex for non-engineering stakeholders.',
    solution: 'Built the full conveyor system in Blender with accurate mechanical joints, belt movement, and product flow. Rendered with cinematic lighting in EEVEE for fast turnaround while maintaining quality.',
    result: 'The animation was used in 3 client pitches and reduced onboarding time for new operators by 40%. The client ordered two more machine animations within the same quarter.',
    featured: true,
    // Add extra image/video sections here. Paste a URL into `url`.
    // Empty url shows a "coming soon" placeholder slot.
    gallery: [
      { type: 'compare', url: '/conveyor-wireframe.jpeg', urlB: '/conveyor-render.jpeg', label: 'Wireframe vs Render', leftLabel: 'WIREFRAME', rightLabel: 'RENDER' },
      { type: 'image', url: '/conveyor-render.jpeg', label: 'Final render' },
    ],
  },
  {
    id: '2',
    slug: 'hydrostatic-drive-explainer',
    title: 'Hydrostatic Drive Explainer',
    category: 'industrial',
    client: 'Engineering Education Platform, UK',
    tools: ['Blender', 'After Effects', 'Adobe Premiere'],
    thumbnail: '/hydrostatic-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/hydrostatic-wireframe.jpeg',
    renderUrl: '/hydrostatic-render.jpeg',
    gallery: [{ type: 'image', url: '/hydrostatic-render.jpeg', label: 'Final render' }],
    description: 'An engineering explainer animation breaking down how a hydrostatic drive system works — from pump to motor — using cutaway views and labelled components.',
    challenge: 'Engineering students struggled to understand the internal flow dynamics of hydrostatic systems from textbooks alone. The platform needed a visual that made the concept instantly clear.',
    solution: 'Created a fully rigged cutaway model with animated fluid flow paths, piston movement, and synchronized motion between the pump and motor. Text callouts added in After Effects.',
    result: 'Published to the platform\'s YouTube channel, the video received 12,000 views in the first month and was cited in course reviews as "the clearest explanation of hydrostatics I\'ve seen."',
    featured: true,
  },
  {
    id: '3',
    slug: 'sorting-machine-visualization',
    title: 'Sorting Machine Visualization',
    category: 'industrial',
    client: 'Logistics Company, Netherlands',
    tools: ['Blender', 'Cycles Render', 'After Effects'],
    thumbnail: '/sorting-render.jpeg',
    videoUrl: '',
    gallery: [{ type: 'image', url: '/sorting-render.jpeg', label: 'Exploded-view render' }],
    description: 'A full machine breakdown animation of an industrial sorting system, showing each stage of the sorting process with exploded-view sequences and component callouts.',
    challenge: 'A logistics company needed to explain their proprietary sorting technology to investors and potential clients without revealing competitive engineering details.',
    solution: 'Designed a stylized, semi-abstract representation of the sorting mechanism that accurately communicated the value proposition while protecting sensitive design elements.',
    result: 'Used in an investor pitch deck that secured €2M in Series A funding. The client quoted the animation as "the key visual that made investors understand the technology instantly."',
    featured: false,
  },
  {
    id: '4',
    slug: 'smart-device-cgi-reveal',
    title: 'Smart Device CGI Reveal',
    category: 'product',
    client: 'Tech Startup, USA',
    tools: ['Blender', 'Cycles Render', 'DaVinci Resolve'],
    thumbnail: '/smart-device-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/smart-device-wireframe.jpeg',
    renderUrl: '/smart-device-render.jpeg',
    gallery: [{ type: 'image', url: '/smart-device-render.jpeg', label: 'Final render' }],
    description: 'A cinematic product launch animation for a smart home device. Featuring dramatic lighting reveals, 360° rotation, and feature highlight sequences for a Kickstarter campaign.',
    challenge: 'The startup needed high-end product visuals comparable to Apple-level CGI but at a fraction of studio cost. Physical prototypes were not yet ready for traditional photography.',
    solution: 'Built the device in Blender with photorealistic PBR materials, HDR studio lighting, and multi-pass rendering. Designed a 60-second reveal sequence with 4 feature highlight moments.',
    result: 'The Kickstarter campaign exceeded its $150,000 goal within 48 hours. The CGI was cited in 3 tech media articles as "some of the best product visualization we\'ve seen at this funding stage."',
    featured: true,
  },
  {
    id: '5',
    slug: 'cosmetic-packaging-3d-ad',
    title: 'Cosmetic Packaging 3D Ad',
    category: 'product',
    client: 'Beauty Brand, France',
    tools: ['Blender', 'EEVEE', 'Photoshop'],
    thumbnail: '/cosmetic-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/cosmetic-wireframe.jpeg',
    renderUrl: '/cosmetic-render.jpeg',
    gallery: [{ type: 'image', url: '/cosmetic-render.jpeg', label: 'Final render' }],
    description: 'Photorealistic CGI product visualization for a luxury cosmetics brand — showcasing a new skincare line with studio-quality renders and a short animated ad.',
    challenge: 'The brand needed product imagery for their website and social media before physical products were ready. Traditional photography timelines and costs were prohibitive for the launch.',
    solution: 'Created photorealistic 3D models of all 5 products in the line with accurate material simulation (glass, liquid, chrome). Delivered both static renders and a 30-second animated ad.',
    result: 'Delivered 2 weeks ahead of schedule. The brand used the CGI exclusively for their product launch, with no physical photography. Sales exceeded projections by 25% in the first month.',
    featured: false,
  },
  {
    id: '9',
    slug: 'automated-egg-grading-system',
    title: 'Automated Egg Grading System',
    category: 'industrial',
    client: 'Egg Grading Equipment Client',
    tools: ['Blender', 'After Effects', 'AutoCAD'],
    thumbnail: '/egg-grading-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/egg-grading-wireframe.jpeg',
    renderUrl: '/egg-grading-render.jpeg',
    gallery: [{ type: 'image', url: '/egg-grading-render.jpeg', label: 'Final render' }],
    description: 'A 3D animation video demonstrating how an automated egg grading system operates, combined with an exploded-view rendering of the full assembly and an updated technical drawing of the product prototype. The project integrated client-supplied video references and a technical prototype drawing into a cohesive, accurate final deliverable.',
    challenge: 'The client needed to clearly communicate how a complex mechanical grading system works — both as a moving animation and as a detailed assembly breakdown. She supplied existing video references and a prototype drawing, and required all elements to be seamlessly integrated while maintaining technical accuracy.',
    solution: 'Incorporated the client\'s video references and selected segments into the new animation, ensuring visual clarity throughout. Produced an exploded rendering to dynamically showcase how all system parts fit together. Delivered a final updated technical drawing reflecting all modifications to the prototype — including new parts and revised measurements.',
    result: 'Delivered a complete package — animation, exploded view, and revised technical drawing — within the agreed timeline, giving the client accurate visuals for both product demonstration and engineering documentation.',
    featured: false,
  },
  {
    id: '8',
    slug: 'scrap-metal-recycling-belt-explainer',
    title: 'Scrap Metal Recycling – Belt Product Explainer',
    category: 'industrial',
    client: 'Scrap Metal Recycling Client',
    tools: ['Blender', 'After Effects', 'DaVinci Resolve'],
    thumbnail: '/scrap-metal-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/scrap-metal-wireframe.jpeg',
    renderUrl: '/scrap-metal-render.jpeg',
    gallery: [{ type: 'image', url: '/scrap-metal-render.jpeg', label: 'Final render' }],
    description: 'An engaging 3D explainer video showcasing a specialized conveyor belt used in the scrap metal recycling process. The video walks through the full recycling workflow — from the initial shredding of large metal pieces such as cars and appliances, through to sorting and final separation stages — with the belt\'s role clearly highlighted at each step.',
    challenge: 'The client needed to communicate the value of their specialized belt within a complex, multi-stage recycling workflow. Generic product descriptions were not enough to help buyers visualize where and how the belt delivers results in a real scrap metal facility.',
    solution: 'Created a dynamic explainer video that illustrated each stage of the scrap metal recycling process with clear visuals. The belt\'s role in facilitating sorting and separation was spotlighted throughout, while the narrative framing aligned with the client\'s commitment to sustainability, resource recovery, and efficient waste management.',
    result: 'Delivered a sales-ready explainer that gives engineers and procurement teams a clear, visual understanding of the belt\'s function within a live recycling line — making the product easier to specify and sell.',
    featured: false,
  },
  {
    id: '7',
    slug: 'ino-usa-corrugated-board-belt-explainer',
    title: 'INO USA – Corrugated Board Process | Belt Product',
    category: 'industrial',
    client: 'INO USA',
    tools: ['Blender', 'After Effects', 'DaVinci Resolve'],
    thumbnail: '/ino-usa-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/ino-usa-wireframe.jpeg',
    renderUrl: '/ino-usa-render.jpeg',
    gallery: [{ type: 'image', url: '/ino-usa-render.jpeg', label: 'Final render' }],
    description: 'A detailed 3D explainer video for INO USA showcasing how industrial conveyor belts — felt, pressure, hot plate, traction, and rough-top — operate within a full corrugated board production line. The video follows the complete manufacturing workflow from paper roll feeding and single facer corrugation through double facer bonding, hot plate curing, cutting, and stacking.',
    challenge: 'The client needed to support the sale of their industrial conveyor belts to engineers, plant managers, and decision-makers. Existing materials did not clearly communicate where each belt type delivers value within a real corrugator line, or why specific belt designs are essential at each production stage.',
    solution: 'Animated the complete corrugated board manufacturing process with belts visually highlighted in operation at each stage. Used close-up views and internal machine cutaways to show how belts interact with paper, rollers, glue systems, and heated plates — emphasizing key performance benefits including heat resistance, moisture control, grip, pressure consistency, and dimensional stability.',
    result: 'Delivered a technically accurate, sales-driven explainer that enables stakeholders to quickly understand belt applications across the corrugator line and confidently choose the right belt solutions for high-speed production.',
    featured: true,
  },
  {
    id: '6',
    slug: 'dental-implant-explainer',
    title: 'Dental Implant Explainer',
    category: 'medical',
    client: 'Dental Clinic Group, UAE',
    tools: ['Blender', 'Cycles Render', 'After Effects', 'Premiere Pro'],
    thumbnail: '/dental-render.jpeg',
    videoUrl: '',
    wireframeUrl: '/dental-wireframe.jpeg',
    renderUrl: '/dental-render.jpeg',
    gallery: [{ type: 'image', url: '/dental-render.jpeg', label: 'Final render' }],
    description: 'A detailed medical animation explaining the dental implant procedure — from bone assessment through implant placement to final crown fitting — for patient education.',
    challenge: 'The clinic needed a way to explain the implant process to anxious patients in a way that was accurate, reassuring, and visually clear. Text brochures were not reducing patient anxiety.',
    solution: 'Created an anatomically accurate, step-by-step surgical animation using subsurface scattering materials for realistic tissue rendering. Narration and subtitles added in post.',
    result: 'The clinic reported a 35% reduction in pre-consultation cancellations after deploying the video on their website and waiting room screens. Three other clinics in the group licensed the video.',
    featured: true,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const index = projects.findIndex((p) => p.slug === slug);
  return {
    prev: index > 0 ? projects[index - 1] : null,
    next: index < projects.length - 1 ? projects[index + 1] : null,
  };
}
