import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'conveyor-belt-system-animation',
    title: 'Conveyor Belt System Animation',
    category: 'industrial',
    client: 'Manufacturing Client, Germany',
    tools: ['Blender', 'After Effects', 'DaVinci Resolve'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder1',
    description: 'A 15-second looping animation showcasing a multi-stage conveyor belt system for a manufacturing facility, complete with moving parts, product flow, and mechanical details.',
    challenge: 'The client needed a clear, accurate visual of their conveyor system to use in sales presentations and training materials. Technical drawings were too complex for non-engineering stakeholders.',
    solution: 'Built the full conveyor system in Blender with accurate mechanical joints, belt movement, and product flow. Rendered with cinematic lighting in EEVEE for fast turnaround while maintaining quality.',
    result: 'The animation was used in 3 client pitches and reduced onboarding time for new operators by 40%. The client ordered two more machine animations within the same quarter.',
    featured: true,
  },
  {
    id: '2',
    slug: 'hydrostatic-drive-explainer',
    title: 'Hydrostatic Drive Explainer',
    category: 'industrial',
    client: 'Engineering Education Platform, UK',
    tools: ['Blender', 'After Effects', 'Adobe Premiere'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder2',
    description: 'An engineering explainer animation breaking down how a hydrostatic drive system works — from pump to motor — using cutaway views and labelled components.',
    challenge: 'Engineering students struggled to understand the internal flow dynamics of hydrostatic systems from textbooks alone. The platform needed a visual that made the concept instantly clear.',
    solution: 'Created a fully rigged cutaway model with animated fluid flow paths, piston movement, and synchronized motion between the pump and motor. Text callouts added in After Effects.',
    result: 'Published to the platform\'s YouTube channel, the video received 12,000 views in the first month and was cited in course reviews as "the clearest explanation of hydrostatics I\'ve seen."',
    featured: true,
  },
  {
    id: '3',
    slug: 'sorting-machine-visualization',
    title: 'Sorting Machine Visualization',
    category: 'industrial',
    client: 'Logistics Company, Netherlands',
    tools: ['Blender', 'Cycles Render', 'After Effects'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder3',
    description: 'A full machine breakdown animation of an industrial sorting system, showing each stage of the sorting process with exploded-view sequences and component callouts.',
    challenge: 'A logistics company needed to explain their proprietary sorting technology to investors and potential clients without revealing competitive engineering details.',
    solution: 'Designed a stylized, semi-abstract representation of the sorting mechanism that accurately communicated the value proposition while protecting sensitive design elements.',
    result: 'Used in an investor pitch deck that secured €2M in Series A funding. The client quoted the animation as "the key visual that made investors understand the technology instantly."',
    featured: false,
  },
  {
    id: '4',
    slug: 'smart-device-cgi-reveal',
    title: 'Smart Device CGI Reveal',
    category: 'product',
    client: 'Tech Startup, USA',
    tools: ['Blender', 'Cycles Render', 'DaVinci Resolve'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder4',
    description: 'A cinematic product launch animation for a smart home device. Featuring dramatic lighting reveals, 360° rotation, and feature highlight sequences for a Kickstarter campaign.',
    challenge: 'The startup needed high-end product visuals comparable to Apple-level CGI but at a fraction of studio cost. Physical prototypes were not yet ready for traditional photography.',
    solution: 'Built the device in Blender with photorealistic PBR materials, HDR studio lighting, and multi-pass rendering. Designed a 60-second reveal sequence with 4 feature highlight moments.',
    result: 'The Kickstarter campaign exceeded its $150,000 goal within 48 hours. The CGI was cited in 3 tech media articles as "some of the best product visualization we\'ve seen at this funding stage."',
    featured: true,
  },
  {
    id: '5',
    slug: 'cosmetic-packaging-3d-ad',
    title: 'Cosmetic Packaging 3D Ad',
    category: 'product',
    client: 'Beauty Brand, France',
    tools: ['Blender', 'EEVEE', 'Photoshop'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder5',
    description: 'Photorealistic CGI product visualization for a luxury cosmetics brand — showcasing a new skincare line with studio-quality renders and a short animated ad.',
    challenge: 'The brand needed product imagery for their website and social media before physical products were ready. Traditional photography timelines and costs were prohibitive for the launch.',
    solution: 'Created photorealistic 3D models of all 5 products in the line with accurate material simulation (glass, liquid, chrome). Delivered both static renders and a 30-second animated ad.',
    result: 'Delivered 2 weeks ahead of schedule. The brand used the CGI exclusively for their product launch, with no physical photography. Sales exceeded projections by 25% in the first month.',
    featured: false,
  },
  {
    id: '6',
    slug: 'dental-implant-explainer',
    title: 'Dental Implant Explainer',
    category: 'medical',
    client: 'Dental Clinic Group, UAE',
    tools: ['Blender', 'Cycles Render', 'After Effects', 'Premiere Pro'],
    thumbnail: '',
    videoUrl: 'https://vimeo.com/placeholder6',
    description: 'A detailed medical animation explaining the dental implant procedure — from bone assessment through implant placement to final crown fitting — for patient education.',
    challenge: 'The clinic needed a way to explain the implant process to anxious patients in a way that was accurate, reassuring, and visually clear. Text brochures were not reducing patient anxiety.',
    solution: 'Created an anatomically accurate, step-by-step surgical animation using subsurface scattering materials for realistic tissue rendering. Narration and subtitles added in post.',
    result: 'The clinic reported a 35% reduction in pre-consultation cancellations after deploying the video on their website and waiting room screens. Three other clinics in the group licensed the video.',
    featured: true,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string): { prev: Project | null; next: Project | null } {
  const index = projects.findIndex((p) => p.slug === slug);
  return {
    prev: index > 0 ? projects[index - 1] : null,
    next: index < projects.length - 1 ? projects[index + 1] : null,
  };
}
